## joint trajectory controller
pro:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  pro_arm_controller1:
    type: position_controllers/JointPositionController
    joint: joint1
    pid: {p: 100.0, i: 0.2, d: 0.2}

  pro_arm_controller2:
    type: position_controllers/JointPositionController
    joint: joint2
    pid: {p: 100.0, i: 0.2, d: 0.2}

  pro_arm_controller3:
    type: position_controllers/JointPositionController
    joint: joint3
    pid: {p: 10.0, i: 0.1, d: 0.1}
  pro_arm_controller4:
    type: position_controllers/JointPositionController
    joint: joint4
    pid: {p: 10.0, i: 0.1, d: 0.1}
  pro_arm_controller5:
    type: position_controllers/JointPositionController
    joint: joint5
    pid: {p: 5.0, i: 0.1, d: 0.1}
  pro_arm_controller6:
    type: position_controllers/JointPositionController
    joint: joint6
    pid: {p: 5.0, i: 0.1, d: 0.1}
gazebo_ros_control:
  pid_gains:
    joint2: {p: 100.0, i: 0.01, d: 10.0}


