## joint trajectory controller
proarm:
  joint1_pos:
    type: effort_controllers/JointPositionController
    joint: joint1      
    pid: {p: 5.0, i: 0.05, d: 0.1}
  joint2_pos:
    type: effort_controllers/JointPositionController
    joint: joint2      
    pid: {p: 5.0, i: 0.0, d: 1.0} 
  joint3_pos:
    type: effort_controllers/JointPositionController
    joint: joint3      
    pid: {p: 10.0, i: 0.00, d: 1.0}
  joint4_pos:
    type: effort_controllers/JointPositionController
    joint: joint4      
    pid: {p: 5.0, i: 0.0, d: 0.1}
  joint5_pos:
    type: effort_controllers/JointPositionController
    joint: joint5      
    pid: {p: 2.0, i: 0.0, d: 0.01}
  joint6_pos:
    type: effort_controllers/JointPositionController
    joint: joint6      
    pid: {p: 1.0, i: 0.001, d: 0.001}

