irb_1400:
  joint_state_controller:
      type: joint_state_controller/JointStateCOntroller
      publish_rate: 50

  joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 100., i: 0.01, d: 10.}
      joint

